go_import_path: github.com/paultyng/go-newrelic

language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
    - os: osx
  fast_finish: true

env:
  GO111MODULE: 'on'

install:
  - make deps

script:
  - make build-ci

sudo: false
